#!/usr/bin/env bash
# ============================================================
# Hermes Agent Setup Script
# Installs and configures Hermes Agent for G Force Ops
# Usage: ./hermes_config/setup_hermes.sh
# ============================================================
set -euo pipefail

HERMES_API_PORT="${HERMES_API_PORT:-8642}"
HERMES_MODEL="${HERMES_MODEL:-openrouter/nousresearch/hermes-3-llama-3.1-70b}"
OPENROUTER_KEY="${OPENROUTER_API_KEY:-}"

echo "🧠 Setting up Hermes Agent for G Force Ops..."

# ── 1. Check if hermes is installed ─────────────────────────────────────
if ! command -v hermes &>/dev/null; then
  echo "📦 Installing Hermes Agent..."
  curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash
  # Reload PATH
  export PATH="$HOME/.hermes/bin:$PATH"
else
  echo "✅ Hermes already installed: $(hermes --version 2>/dev/null || echo 'version unknown')"
fi

# ── 2. Configure API key ─────────────────────────────────────────────────
if [[ -z "$OPENROUTER_KEY" ]]; then
  echo "⚠️  OPENROUTER_API_KEY not set. Trying 1Password..."
  OPENROUTER_KEY=$(op read "op://Private/GForceOps/openrouter_api_key" 2>/dev/null || echo "")
fi

if [[ -z "$OPENROUTER_KEY" ]]; then
  echo "❌ No API key found. Set OPENROUTER_API_KEY or configure via 1Password."
  echo "   Alternative: Run 'hermes setup --portal' for Nous Portal auth."
  exit 1
fi

# ── 3. Write .env ─────────────────────────────────────────────────────────
HERMES_DIR="$HOME/.hermes"
mkdir -p "$HERMES_DIR"

cat > "$HERMES_DIR/.env" <<EOF
# G Force Ops — Hermes Agent Configuration
# Generated by setup_hermes.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — this file lives in ~/.hermes/

OPENROUTER_API_KEY=${OPENROUTER_KEY}
API_SERVER_ENABLED=true
API_SERVER_PORT=${HERMES_API_PORT}
HERMES_MODEL=${HERMES_MODEL}
LOG_LEVEL=${LOG_LEVEL:-INFO}
EOF

echo "✅ ~/.hermes/.env written"

# ── 4. Write config.yaml ────────────────────────────────────────────────
cat > "$HERMES_DIR/config.yaml" <<YAML
# Hermes Agent — G Force Ops Config
# Model: Hermes 3 via OpenRouter (falls back to Mercury Hermes for fast tasks)

model:
  provider: openrouter
  name: nousresearch/hermes-3-llama-3.1-70b
  fallback: nousresearch/mercury-hermes

api_server:
  enabled: true
  port: ${HERMES_API_PORT}
  host: "127.0.0.1"

memory:
  enabled: true
  backend: local
  path: ~/.hermes/memory

skills:
  - name: github_skill
    path: ${PWD}/agents/hermes/skills/github_skill.py
    enabled: true
  - name: gripper_skill
    path: ${PWD}/agents/hermes/skills/gripper_skill.py
    enabled: true

persona: |
  You are the G Force Operations Agent — an expert AI assistant for Robert Bailey
  at Power Connection AI and Connected Energy Services.
  
  You manage GitHub repositories, control hardware (OpenClaw gripper via Raspberry Pi),
  monitor CI/CD pipelines, and assist with energy operations (ERCOT, Power Connection).
  
  You have persistent memory across sessions. Always cite your sources.
  For hardware commands, confirm before executing on physical devices.
  For litigation/legal tasks, always flag for attorney review.

crons:
  - schedule: "*/15 * * * *"
    task: "Check GitHub CI status for gforce-repo-ops and alert if any failures"
    
  - schedule: "0 8 * * *"
    task: "Daily briefing: summarize open GitHub issues, PR status, and system health"
YAML

echo "✅ ~/.hermes/config.yaml written"

# ── 5. Verify setup ──────────────────────────────────────────────────────
echo ""
echo "🎯 Hermes Agent configured!"
echo ""
echo "   Model:      $HERMES_MODEL"
echo "   API Server: http://127.0.0.1:${HERMES_API_PORT}/v1"
echo "   Memory:     ~/.hermes/memory/"
echo ""
echo "To start Hermes:"
echo "   hermes gateway        # Start with full gateway (messaging)"
echo "   hermes --tui          # Start with terminal UI"
echo "   hermes api            # API server only (for integration)"
echo ""
echo "Test the API:"
echo '   curl http://127.0.0.1:'"${HERMES_API_PORT}"'/v1/models'
